# Generated by Django 3.1.2 on 2021-07-21 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 21, 14, 21, 27, 911500, tzinfo=utc)),
        ),
    ]
